### ISSUE TITLE
ping: unknown host gateway

### ISSUE THREAD

**Issue by alexfrancow** [europa502/shARP#1]
$ ./shARP.sh -d ens33
ping: unknown host gateway
gateway not found

$ arp
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.1.1              ether   2c:95:7f:0a:6e:30   C                     ens33

**Comment by GuillermoElectrico** [comment]
I have solved this problem by editing the hosts file and adding the gateway ip with the name "gateway".

Not ideal, but it works.

**Comment by europa502** [comment]
This problem arises when you r on ubuntu based os. Just change in the source code to 'arp' where ever 'arp --gateway' is written. 
Hope this might help.
